import {LedgerTools} from "./view";
import {LedgerSlip,type QuoteDraft} from "./slip";
import {ReceiptImport} from "./receipts";
export const dynamic="force-dynamic";
type Bet={id:string;mode:string;currency:string;stake:string;terms:Record<string,unknown>;settlement:{status:string;profit?:string};closing:{status:string;price_american?:number;clv_percent?:number;verification?:unknown}};
export default async function Page({searchParams}:{searchParams:Promise<{quote?:string;kind?:string;side?:string}>}){
 const query=await searchParams;
 let draft:QuoteDraft|null=null,evidence:unknown=null;
 async function get(path:string){try{const r=await fetch(`${process.env.FANTASY_API_URL||"http://api:8000"}/api/v1/ledger${path}`,{headers:{Authorization:`Bearer ${process.env.FANTASY_API_TOKEN||""}`},cache:"no-store",signal:AbortSignal.timeout(15000)});return r.ok?await r.json():null;}catch{return null;}}
 [draft,evidence]=await Promise.all([query.quote&&query.kind&&query.side?get(`/quote/${encodeURIComponent(query.kind)}/${encodeURIComponent(query.quote)}?side=${encodeURIComponent(query.side)}`):null,get("/closing-evidence-status")]);
 let data:{items:Bet[];exposure:unknown;policies:Record<string,unknown>}|null=null;
 try{const r=await fetch(`${process.env.FANTASY_API_URL||"http://api:8000"}/api/v1/ledger`,{headers:{Authorization:`Bearer ${process.env.FANTASY_API_TOKEN||""}`},cache:"no-store",signal:AbortSignal.timeout(15000)});if(r.ok)data=await r.json();}catch{}
 return <main className="mx-auto max-w-6xl space-y-5 p-6"><h1 className="text-3xl font-bold">Betting ledger</h1><p>Manual and paper singles, settlement audit, and gross stake exposure. No automatic betting.</p><p className="text-amber-300">Verified CLV requires reviewed matching receipt/quote rules AND evidence of an official closing price. Other observations remain labeled proxies. CLV here means same-line decimal-price improvement, not no-vig expected return.</p>{query.quote&&(draft?<LedgerSlip key={`${query.quote}:${query.side}`} draft={draft}/>:<p role="alert">The selected quote could not be resolved. Return to Best Bets and refresh; no wager was recorded.</p>)}<details><summary>Closing verification coverage and requirements</summary><pre className="whitespace-pre-wrap text-sm">{JSON.stringify(evidence,null,2)}</pre></details>{!data?<p>Ledger service unavailable.</p>:<><ReceiptImport/><h2 className="text-xl">Exposure and controls</h2><p>{Object.keys(data.policies).length?"Saved policies shown below. Unset dimensions have no limit.":"Unconfigured — no bankroll or stake limits have been assumed."} Actual and paper stakes are separate; related bets are not netted.</p><pre className="overflow-auto rounded bg-slate-900 p-3 text-sm">{JSON.stringify({exposure:data.exposure,policies:data.policies},null,2)}</pre><details><summary>Advanced manual entry, settlements and limits</summary><LedgerTools/></details><h2 className="text-xl">Entries ({data.items.length})</h2>{!data.items.length?<p>No bets recorded. Recommendations are not wagers.</p>:data.items.map(b=><article key={b.id} className="space-y-2 rounded border border-slate-700 p-4"><p>{b.mode} · {b.currency} {b.stake} · {b.settlement.status} · Profit {b.settlement.profit??"pending"}</p><p className="break-all text-xs">{b.id}</p><p>{String(b.terms.book)} · {String(b.terms.market)} · {String(b.terms.side)} · {String(b.terms.line??"")}</p><p>Closing evidence: {b.closing.status} {b.closing.price_american??""} {b.closing.clv_percent!=null?`· CLV ${b.closing.clv_percent}%`:""}</p><details><summary>Frozen placement and closing evidence</summary><pre className="overflow-auto text-xs">{JSON.stringify({terms:b.terms,closing:b.closing},null,2)}</pre></details></article>)}</>}</main>;
}
