"use client";
import {useRef,useState} from "react";
import {ledgerAction} from "./actions";
export type QuoteDraft={terms:{game_id:string;kind:"team"|"player";player_id:string|null;market:string;side:string;line:number|null;price_american:number;book:string;quote_id:string};label:string;player:string|null;observed_at:string;availability:string};
export function LedgerSlip({draft}:{draft:QuoteDraft}){
 const [mode,setMode]=useState("paper"),[stake,setStake]=useState(""),[currency,setCurrency]=useState("USD"),[price,setPrice]=useState(String(draft.terms.price_american)),[rules,setRules]=useState(""),[product,setProduct]=useState(""),[jurisdiction,setJurisdiction]=useState(""),[at,setAt]=useState("");
 const [busy,setBusy]=useState(false),[result,setResult]=useState(""),[saved,setSaved]=useState(false);
 const attempt=useRef<{signature:string;body:unknown}|null>(null);
 async function submit(action:string){
  setBusy(true);try{
   const base={...draft.terms,mode,stake,currency,price_american:mode==="paper"?draft.terms.price_american:Number(price),settlement_rules:rules,product:product||null,jurisdiction:jurisdiction||null,period:"full_game"};
   const signature=JSON.stringify({...base,at});
   if(attempt.current&&attempt.current.signature!==signature){setResult("Details changed after a submission. Check the ledger for the earlier attempt before starting a new entry.");return;}
   const body=attempt.current?.body||{...base,request_id:crypto.randomUUID(),placed_at:at?new Date(at).toISOString():new Date().toISOString()};
   if(action==="bets")attempt.current={signature,body};
   const reply=await ledgerAction(action,body);setResult(JSON.stringify(reply,null,2));
   if(action==="bets"&&"ok" in reply&&reply.ok)setSaved(true);
  }catch{setResult("Check placement date and form values.");}finally{setBusy(false);}
 }
 return <section className="space-y-3 rounded border border-emerald-700 p-4"><h2 className="text-xl">Log this Best Bets offer</h2><p>{draft.label} {draft.player?`· ${draft.player}`:""}</p><p>{draft.terms.book} · {draft.terms.market} · {draft.terms.side} {draft.terms.line??""} · {draft.terms.price_american}</p><p className="text-sm text-amber-300">Offer status: {draft.availability}. Seen {draft.observed_at}. This does not place a wager. Actual mode records an existing receipt; paper mode requires a current pregame quote.</p><div className="grid gap-3 sm:grid-cols-2"><label>Mode<select className="block w-full bg-slate-900 p-2" value={mode} onChange={e=>setMode(e.target.value)}><option value="paper">Paper simulation</option><option value="actual">Already placed elsewhere</option></select></label><label>Stake<input className="block w-full bg-slate-900 p-2" type="number" min="0.01" step="0.01" value={stake} onChange={e=>setStake(e.target.value)}/></label><label>Currency<input className="block w-full bg-slate-900 p-2" maxLength={3} value={currency} onChange={e=>setCurrency(e.target.value.toUpperCase())}/></label><label>Receipt American odds<input className="block w-full bg-slate-900 p-2" type="number" value={price} disabled={mode==="paper"} onChange={e=>setPrice(e.target.value)}/></label><label>Placement time (your local time; required for actual)<input className="block w-full bg-slate-900 p-2" type="datetime-local" value={at} onChange={e=>setAt(e.target.value)}/></label><label>Book product, if known<input className="block w-full bg-slate-900 p-2" value={product} onChange={e=>setProduct(e.target.value)}/></label><label>Receipt jurisdiction, if known<input className="block w-full bg-slate-900 p-2" value={jurisdiction} onChange={e=>setJurisdiction(e.target.value)}/></label></div><label className="block">Settlement rules / receipt notes (not independently verified)<textarea className="block w-full bg-slate-900 p-2" value={rules} onChange={e=>setRules(e.target.value)}/></label><div className="flex gap-3"><button className="rounded border p-2 disabled:opacity-50" disabled={busy||!stake||!rules||saved||(mode==="actual"&&!at)} onClick={()=>submit("preflight")}>Check exposure</button><button className="rounded border border-emerald-500 p-2 disabled:opacity-50" disabled={busy||!stake||!rules||saved||(mode==="actual"&&!at)||(mode==="paper"&&draft.availability!=="current_pregame_offer")} onClick={()=>submit("bets")}>{saved?"Recorded":"Record in ledger"}</button></div><pre className="whitespace-pre-wrap text-sm" role="status">{result}</pre></section>;
}
