"use client";
import {useState} from "react";
import {ledgerAction} from "./actions";
export function LedgerTools(){
 const [action,setAction]=useState("bets"),[body,setBody]=useState(""),[result,setResult]=useState(""),[busy,setBusy]=useState(false);
 function example(kind:string){
  setAction(kind); setResult("");
  setBody(JSON.stringify(kind==="policy"?{currency:"USD",single:null,total:null,sport:null,game:null,player:null,book:null}:kind==="capture-closes"?{}:{request_id:crypto.randomUUID(),mode:"paper",currency:"USD",stake:"1.00",placed_at:new Date().toISOString(),game_id:"REPLACE_WITH_GAME_UUID",kind:"team",market:"moneyline",side:"home",line:null,price_american:-110,book:"EXACT_QUOTE_SOURCE",settlement_rules:"REPLACE_WITH_BOOK_RULES"},null,2));
 }
 return <section className="space-y-3 rounded border border-slate-700 p-4"><h2 className="text-xl">Ledger tools</h2><p className="text-sm text-slate-400">Advanced entry: exact app game/player IDs and book source are required. Paper mode does not place a wager. Actual mode records a wager already placed elsewhere. Returned settlement amounts include stake. No limits are chosen for you.</p><div className="flex gap-3 flex-wrap">{["bets","preflight","policy","capture-closes"].map(a=><button className="rounded border p-2" key={a} onClick={()=>example(a)}>{a}</button>)}</div><label className="block">Action <input aria-label="Action" className="w-full bg-slate-900 p-2" value={action} onChange={e=>setAction(e.target.value)}/></label><p className="text-sm text-slate-400">To settle or correct: action bets/BET_UUID/settlements; JSON fields request_id, status (open/won/lost/push/void/cashout), returned, evidence. Each correction needs a new request ID.</p><textarea aria-label="Ledger request JSON" className="w-full rounded bg-slate-900 p-3 font-mono text-sm" rows={15} value={body} onChange={e=>setBody(e.target.value)}/><button disabled={busy||!body} className="rounded border p-2 disabled:opacity-50" onClick={async()=>{setBusy(true);try{const parsed=JSON.parse(body);if(action==="policy"&&!window.confirm("Save these absolute stake limits? Null fields are unlimited. This replaces the previous policy for this currency."))return;setResult(JSON.stringify(await ledgerAction(action,parsed),null,2));}catch{setResult("Invalid JSON");}finally{setBusy(false);}}}>{busy?"Working…":"Submit"}</button><pre className="whitespace-pre-wrap text-sm" role="status">{result}</pre></section>;
}
