"""nfl foundation

Revision ID: 0001_nfl_foundation
Revises: 
Create Date: 2026-08-20 12:43:44.045082
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001_nfl_foundation'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_artifacts',
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('trained_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seasons_used', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=False),
    sa.Column('brier', sa.Float(), nullable=True),
    sa.Column('log_loss', sa.Float(), nullable=True),
    sa.Column('calibration_error', sa.Float(), nullable=True),
    sa.Column('passed_gate', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    op.create_table('teams',
    sa.Column('espn_id', sa.String(length=16), nullable=False),
    sa.Column('nflverse_abbr', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_id'),
    sa.UniqueConstraint('nflverse_abbr')
    )
    op.create_table('games',
    sa.Column('nflverse_game_id', sa.String(length=32), nullable=True),
    sa.Column('espn_event_id', sa.String(length=32), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.String(length=8), nullable=True),
    sa.Column('game_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('home_team_id', sa.UUID(), nullable=True),
    sa.Column('away_team_id', sa.UUID(), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('home_rest', sa.Integer(), nullable=True),
    sa.Column('away_rest', sa.Integer(), nullable=True),
    sa.Column('div_game', sa.Boolean(), nullable=True),
    sa.Column('roof', sa.String(length=16), nullable=True),
    sa.Column('surface', sa.String(length=24), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('wind', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_event_id'),
    sa.UniqueConstraint('nflverse_game_id')
    )
    op.create_index('ix_games_season_week', 'games', ['season', 'week'], unique=False)
    op.create_table('players',
    sa.Column('gsis_id', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('current_team_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['current_team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gsis_id')
    )
    op.create_table('model_predictions',
    sa.Column('artifact_version', sa.String(length=64), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_external_ids',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_player_external_source_id')
    )
    op.create_table('player_game_stats',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('stat_type', sa.String(length=48), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', 'stat_type', name='uq_player_game_stat')
    )
    op.create_table('player_prop_lines',
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=True),
    sa.Column('stat_type', sa.String(length=48), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('over_price_american', sa.Integer(), nullable=True),
    sa.Column('under_price_american', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_prop_lines_latest', 'player_prop_lines', ['player_id', 'stat_type', 'source', 'observed_at'], unique=False)
    op.create_table('team_market_lines',
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('line', sa.Float(), nullable=True),
    sa.Column('price_american', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('line_type', sa.String(length=8), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_team_lines_latest', 'team_market_lines', ['game_id', 'market', 'side', 'source', 'observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_team_lines_latest', table_name='team_market_lines')
    op.drop_table('team_market_lines')
    op.drop_index('ix_prop_lines_latest', table_name='player_prop_lines')
    op.drop_table('player_prop_lines')
    op.drop_table('player_game_stats')
    op.drop_table('player_external_ids')
    op.drop_table('model_predictions')
    op.drop_table('players')
    op.drop_index('ix_games_season_week', table_name='games')
    op.drop_table('games')
    op.drop_table('teams')
    op.drop_table('model_artifacts')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
