"use client";
import {useState} from "react";
type Player={player_id:string;name:string;position:string;team:string;weekly_points:number|null;ros:{full_ros_value?:number|null;known_remaining_games:number;known_schedule_subtotal:number|null;per_game:{status:string;modeled_subtotal?:number|null;missing_scoring_keys?:string[];games?:number}}};
export type DecisionModels={status:string;week:number;generated_at:string;coverage:Record<string,unknown>;prospective?:{status:string;total_forecasts?:number;counts?:Record<string,number>;ros?:{forecasts:number;counts:Record<string,number>};weekly?:{forecasts:number;counts:Record<string,number>};metrics?:{league_id:string;n:number;baseline_mae:number;candidate_mae:number}[]};notes:string[];players:Player[];matchup:{status:string;your_pregame_projection:number|null;opponent_pregame_projection:number|null;projected_margin:number|null;reason:string};waivers:{status:string;moves:{add_id:string;add:string;drop:string;lineup_gain:number}[]}};
const num=(n?:number|null)=>n==null?"—":n.toFixed(2);
export function FantasyModels({data}:{data:DecisionModels & {specialist_validation?:unknown}}) {
 const [search,setSearch]=useState("");
 const [a,setA]=useState<string[]>([]),[b,setB]=useState<string[]>([]);
 const subtotal=(ids:string[])=>{const ps=ids.map(id=>data.players.find(p=>p.player_id===id));return ps.length&&ps.every(p=>p?.ros.known_schedule_subtotal!=null)?ps.reduce((v,p)=>v+(p?.ros.known_schedule_subtotal||0),0):null;};
 return <>
 <details className="rounded border border-slate-700 p-4"><summary>Independent specialist evaluation</summary><p className="text-sm text-slate-400">Historical holdout results for kicking components only. Not full ROS validation or automatic model promotion. Rookie and defense coverage status is reported separately.</p><pre className="overflow-auto text-xs">{JSON.stringify(data.specialist_validation??{status:"not_evaluated"},null,2)}</pre></details>
  <section className="rounded border border-emerald-800 p-4"><h2 className="text-xl">Prospective validation · {data.prospective?.status||"not started"}</h2><p>{data.prospective?.total_forecasts||0} frozen player-game forecasts · {data.prospective?.counts?.graded||0} graded · {data.prospective?.ros?.forecasts||0} frozen ROS forecasts · {data.prospective?.weekly?.forecasts||0} frozen weekly decision sets</p><p className="text-sm text-slate-400">Checked every 15 minutes. First eligible pregame capture stays unchanged; grades follow corrected finals. Scoring rules are frozen, and different scoring cohorts are evaluated separately. No retrospective predictions are counted as prospective evidence.</p><details><summary>Validation details</summary><pre className="overflow-auto text-xs">{JSON.stringify(data.prospective,null,2)}</pre></details></section>
  <section className="rounded border border-slate-700 p-4"><h2 className="text-xl">Week {data.week} matchup candidate · {data.matchup.status.replaceAll("_"," ")}</h2><p>Your full-week provider projection: {num(data.matchup.your_pregame_projection)} · Opponent: {num(data.matchup.opponent_pregame_projection)} · Eligible pregame margin: {num(data.matchup.projected_margin)}</p><p className="text-sm text-amber-200">{data.matchup.reason} These full-week projections must not be added to live scores.</p></section>
  <section className="rounded border border-slate-700 p-4"><h2 className="text-xl">Waiver add/drop model · {data.waivers.status.replaceAll("_"," ")}</h2><p className="text-sm text-slate-400">Ranks modeled gains in the best legal lineup, including flex/superflex. Current starters are protected. No FAAB price is guessed.</p>{data.waivers.moves.length?data.waivers.moves.map(m=><p key={m.add_id}>Add {m.add}, drop {m.drop}: +{num(m.lineup_gain)} weekly lineup points</p>):<p>No actionable moves qualified under the current coverage and timing checks.</p>}</section>
  <section className="space-y-3 rounded border border-slate-700 p-4"><h2 className="text-xl">ROS trade research</h2><p className="text-sm text-amber-200">Through week 18, conditional on playing with a constant role. Full ROS estimates require complete schedule and scoring coverage; missing evidence stays explicit. This is not a validated trade fairness verdict or dynasty value.</p><p>Side A known-schedule subtotal: {num(subtotal(a))} · Side B: {num(subtotal(b))}</p><div className="text-sm">{data.players.filter(p=>a.includes(p.player_id)||b.includes(p.player_id)).map(p=><p key={p.player_id}>{p.name}: full-coverage ROS candidate {num(p.ros.full_ros_value)}</p>)}</div>
   {[{name:"A",ids:a,set:setA,other:b},{name:"B",ids:b,set:setB,other:a}].map(side=><div key={side.name}><label>Side {side.name} <select className="max-w-full rounded bg-slate-900 p-2" value="" onChange={e=>{if(e.target.value)side.set([...side.ids,e.target.value]);}}><option value="">Add player…</option>{data.players.filter(p=>!side.ids.includes(p.player_id)&&!side.other.includes(p.player_id)).map(p=><option key={p.player_id} value={p.player_id}>{p.name} · {p.position}</option>)}</select></label><div>{side.ids.map(id=><button className="m-1 rounded border border-slate-600 px-2" key={id} onClick={()=>side.set(side.ids.filter(x=>x!==id))}>{data.players.find(p=>p.player_id===id)?.name} ×</button>)}</div></div>)}
   <label className="block">Player coverage <input className="ml-2 rounded bg-slate-900 p-2" placeholder="Filter by name or team" value={search} onChange={e=>setSearch(e.target.value)}/></label>
   <div className="max-h-96 overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{["Player","Per-game modeled subtotal","Known remaining games","Known-schedule subtotal","Coverage"].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{data.players.filter(p=>`${p.name} ${p.team}`.toLowerCase().includes(search.toLowerCase())).map(p=><tr className="border-t border-slate-800" key={p.player_id}><td className="p-2">{p.name} · {p.position}</td><td>{num(p.ros.per_game.modeled_subtotal)}</td><td>{p.ros.known_remaining_games}</td><td>{num(p.ros.known_schedule_subtotal)}</td><td>{p.ros.per_game.status.replaceAll("_"," ")} · {p.ros.per_game.games||0} games{p.ros.per_game.missing_scoring_keys?.length?` · omitted: ${p.ros.per_game.missing_scoring_keys.join(", ")}`:""}</td></tr>)}</tbody></table></div>
  </section><details className="rounded border border-slate-700 p-3"><summary>Input coverage · {data.generated_at}</summary><pre className="overflow-auto text-xs">{JSON.stringify(data.coverage,null,2)}</pre>{data.notes.map(n=><p key={n} className="text-sm">{n}</p>)}</details>
 </>;
}
