"use client";
import {useState} from "react";
type Player={player_id:string;name:string;position:string;team:string;injury_status:string|null;history_through:string|null;roster_ids:number[];weekly_evidence?:{status:string;points:number|null;week:number;source:string};ros:{full_ros_value:number|null};value:{status:string;conditional_points_per_game:number|null;above_available_replacement_per_game:number|null;replacement_player:string|null;blockers:string[]}};
export type ValueData={status:string;league_id:string;generated_at:string;valuation_version:string;input_timestamps:Record<string,string>;valuation_notes:string[];value_coverage:Record<string,number>;players:Player[];trade_candidates:{give:string;receive:string;other_team:string;your_gain:number;their_gain:number}[]};
const num=(n:number|null|undefined)=>n==null?"—":n.toFixed(2);
type Impact={status:string;blockers?:string[];note?:string;side_a?:{team:string;conditional_lineup_gain:number|null};side_b?:{team:string;conditional_lineup_gain:number|null};detail?:string;market?:{status:string;captured_at?:string;note?:string;format?:Record<string,unknown>;players?:{player_id:string;value:number|null}[]}};
export function Values({data}:{data:ValueData}) {
 const [search,setSearch]=useState(""),[position,setPosition]=useState("");
 const [a,setA]=useState<string[]>([]),[b,setB]=useState<string[]>([]);
 const [plans,setPlans]=useState<Record<string,{add:string[];drop:string[]}>>({a:{add:[],drop:[]},b:{add:[],drop:[]}});
 const [result,setResult]=useState<Impact|null>(null),[busy,setBusy]=useState(false);
 async function evaluate(){setBusy(true);setResult(null);try{
  const r=await fetch("/api/fantasy/trade/roster-impact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({league_id:data.league_id,side_a_player_ids:a,side_b_player_ids:b,a:plans.a,b:plans.b})});
  const body=await r.json();setResult(r.ok?body:{status:"unavailable",detail:body.detail||body.error||"Trade service unavailable"});
 }catch{setResult({status:"unavailable",detail:"Could not reach trade service"});}finally{setBusy(false);}}
 return <>
 <section className="rounded border border-amber-800 p-4"><p>Research model · {data.valuation_version} · calculated {new Date(data.generated_at).toLocaleString()}</p><p>{Object.entries(data.value_coverage).map(([k,v])=>`${v} ${k.replaceAll("_"," ")}`).join(" · ")}</p>{data.valuation_notes.map(n=><p className="mt-1 text-sm text-slate-400" key={n}>{n}</p>)}<details><summary>Source freshness (not the calculation time)</summary>{Object.entries(data.input_timestamps).map(([k,v])=><p key={k}>{k}: {new Date(v).toLocaleString()}</p>)}</details></section>
 <section className="space-y-3 rounded border border-slate-700 p-4"><h2 className="text-xl">Two-sided trade impact</h2><p className="text-sm text-slate-400">Each side gives the players selected. For uneven trades, explicitly add free agents and drop rostered players to preserve each roster&apos;s size. Hypothetical only: waiver availability, FAAB, locks and trade processing are not guaranteed.</p>
 {[{name:"A",ids:a,set:setA,other:b},{name:"B",ids:b,set:setB,other:a}].map(s=><div key={s.name}><label>Side {s.name} gives <select disabled={busy} value="" className="max-w-full rounded bg-slate-900 p-2" onChange={e=>{if(e.target.value){s.set([...s.ids,e.target.value]);setResult(null);}}}><option value="">Add player…</option>{data.players.filter(p=>p.roster_ids.length&&!s.ids.includes(p.player_id)&&!s.other.includes(p.player_id)).map(p=><option key={p.player_id} value={p.player_id}>{p.name} · {p.position} · roster {p.roster_ids.join(",")}</option>)}</select></label><div>{s.ids.map(id=><button disabled={busy} className="m-1 rounded border px-2" key={id} onClick={()=>{s.set(s.ids.filter(x=>x!==id));setResult(null);}}>{data.players.find(p=>p.player_id===id)?.name} ×</button>)}</div></div>)}
 <details><summary>Uneven-trade add/drop plan</summary>{["a","b"].map(side=><div key={side} className="my-3"><b>Side {side.toUpperCase()}</b>{(["add","drop"] as const).map(kind=><div key={kind}><label>{kind==="add"?"Add free agent":"Drop roster player"} <select disabled={busy} className="max-w-full bg-slate-900 p-2" value="" onChange={e=>{if(e.target.value){setPlans({...plans,[side]:{...plans[side],[kind]:[...plans[side][kind],e.target.value]}});setResult(null);}}}><option value="">Choose…</option>{data.players.filter(p=>!a.includes(p.player_id)&&!b.includes(p.player_id)&&!Object.values(plans).some(v=>v.add.includes(p.player_id)||v.drop.includes(p.player_id))&&(kind==="add"?!p.roster_ids.length:p.roster_ids.some(id=>data.players.find(p=>p.player_id===(side==="a"?a:b)[0])?.roster_ids.includes(id)))).map(p=><option key={p.player_id} value={p.player_id}>{p.name} · {p.position}</option>)}</select></label>{plans[side][kind].map(id=><button disabled={busy} className="m-1 rounded border px-2" key={id} onClick={()=>{setPlans({...plans,[side]:{...plans[side],[kind]:plans[side][kind].filter(x=>x!==id)}});setResult(null);}}>{data.players.find(p=>p.player_id===id)?.name} ×</button>)}</div>)}</div>)}</details>
 <button disabled={busy||!a.length||!b.length} className="rounded border border-emerald-700 p-2 disabled:opacity-40" onClick={evaluate}>{busy?"Calculating…":"Compare roster impact"}</button>
 {result?.market&&<div className="rounded border border-slate-700 p-3"><a className="text-emerald-300 underline" href="https://fantasycalc.com" target="_blank" rel="noreferrer">FantasyCalc market values</a><p>{result.market.status.replaceAll("_"," ")} · captured {result.market.captured_at||"not available"}</p>{result.market.players?.map(p=><p key={p.player_id}>{data.players.find(x=>x.player_id===p.player_id)?.name||p.player_id}: {num(p.value)}</p>)}<p className="text-xs text-slate-400">{result.market.note}</p><p className="text-xs">Format: {JSON.stringify(result.market.format)}</p></div>}
 {result&&<div role="status"><p>{result.status.replaceAll("_"," ")}</p>{result.blockers?.map(x=><p className="text-amber-200" key={x}>{x.replaceAll("_"," ")}</p>)}{result.status==="research_candidate"&&[result.side_a,result.side_b].map((s,i)=><p key={i}>{s?.team}: {num(s?.conditional_lineup_gain)} conditional lineup points/game gained</p>)}<p>{result.detail||result.note}</p></div>}
 <h3 className="text-lg">Mutual lineup-improvement candidates</h3>{data.trade_candidates.length?data.trade_candidates.map((r,i)=><p key={i}>Give {r.give}, receive {r.receive} from {r.other_team}: you +{num(r.your_gain)}, them +{num(r.their_gain)} conditional points/game. Market price not assessed.</p>):<p className="text-slate-400">No candidate qualified. Search is limited to eight modeled players per roster; missing history, injury flags and stale inputs can block suggestions.</p>}</section>
 <section className="rounded border border-slate-700 p-4"><h2 className="text-xl">Weekly coverage: rookies, kickers, defenses and veterans</h2><p className="text-sm text-amber-200">Separate provider forecasts, not our historical model or ROS values. Search and position filters below also filter this list. Started, stale and missing forecasts stay unavailable.</p><div className="max-h-64 overflow-auto">{data.players.filter(p=>(!position||p.position===position)&&`${p.name} ${p.team}`.toLowerCase().includes(search.toLowerCase())).map(p=><p className="border-b border-slate-800 py-1 text-sm" key={p.player_id}>{p.name} · {p.position} · Week {p.weekly_evidence?.week}: {p.weekly_evidence?.status==="pregame_provider_projection"?num(p.weekly_evidence.points):"—"} · {p.weekly_evidence?.source} · {p.weekly_evidence?.status.replaceAll("_"," ")||"missing evidence"}</p>)}</div></section>
 <section><label>Find player <input value={search} onChange={e=>setSearch(e.target.value)} className="m-2 rounded bg-slate-900 p-2" placeholder="Name or team"/></label><label>Position <select value={position} onChange={e=>setPosition(e.target.value)} className="rounded bg-slate-900 p-2"><option value="">All</option>{["QB","RB","WR","TE","K","DEF","DST"].map(p=><option key={p}>{p}</option>)}</select></label><div className="max-h-[36rem] overflow-auto"><table className="w-full text-left text-sm"><thead><tr>{["Player","Conditional points/game","Full-coverage ROS","Above replacement/game","Evidence"].map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{data.players.filter(p=>(!position||p.position===position)&&`${p.name} ${p.team}`.toLowerCase().includes(search.toLowerCase())).map(p=><tr key={p.player_id} className="border-t border-slate-800"><td className="p-2">{p.name}<div className="text-slate-400">{p.position} · {p.team} · {p.roster_ids.length?"Rostered":"Unowned"}</div></td><td>{num(p.value.conditional_points_per_game)}</td><td>{num(p.ros.full_ros_value)}</td><td>{num(p.value.above_available_replacement_per_game)}<div className="text-xs text-slate-400">vs {p.value.replacement_player||"unknown"}</div></td><td>{p.value.blockers.join(", ")||"Research candidate"}<div className="text-xs">Last result: {p.history_through?.slice(0,10)||"unknown"}</div></td></tr>)}</tbody></table></div></section>
 </>;
}
